FROM node:latest
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
COPY insertDocuments.js .
COPY serverWithoutBcrypt.js .
COPY startScript.sh .
RUN chmod +x ./startScript.sh
CMD ["./startScript.sh"]