FROM node:latest
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
COPY insertDocuments.js .
COPY serverWithoutBcrypt.js .
COPY server.sh .
RUN chmod +x ./server.sh
CMD ["./server.sh"]